### ISSUE TITLE
A quoi sert ce repo?

### ISSUE THREAD

**Issue by MacKentoch** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#1]
Juste mon ignorance mais je me demande pourquoi ce repo existe puisque l'attestation dérogatoire est possible via : https://github.com/LAB-MI/deplacement-covid-19 non?

S'il faut faire des MAJ pour refaire un nouveau?

Merci d'avance et prenez soin de vous tous.

**Comment by gjgd** [comment]
Je suppose que l'idée est: Une attestion = un repo.
- https://github.com/LAB-MI/deplacement-covid-19 -> confinement avril-mai
- https://github.com/LAB-MI/attestation-couvre-feu-covid-19 -> couvre-feu octobre
- https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020 -> confinement octobre

**Comment by patheticcockroach** [comment]
C'est moi ou il est vide le dépôt par contre ? (en voyant le titre du ticket, je me suis dit que le dépôt vide était le sens de la question ^^)

**Comment by repsorp** [comment]
- A quoi sert ce repo ?
- A prétendre justifier ce mensonge "Le code source de ce service est consultable sur GitHub."

**Comment by AzaleeBleue** [comment]
Il est vrai que mettre un lien vers le dépôt du générateur d'attestation dérogatoire numérique et ne pas y publier le code source, ça fait amateur.
Mais faut il attendre encore quelque chose de la brochette d'incompétents qui a kidnappée la présidence ? Ils n'ont été mis là que pour une chose : enrichir le plus possible les plus riches dont ils sont les marionnettes. Et c'est la seule chose qu'ils savent faire : baisser les impôts des plus riches, casser les services publics par des mesures de réduction des dépenses, creuser les déficits pour justifier de future réduction des dépenses (par exemple le "trou" de la Sécu qui ne va pas tarder à se retrouver mis en avant à cause du coût faramineux des tests covid en comparaison avec leur coût dans les autres pays européens, les exonérations de taxes pour soutenir les entreprises en cette période et dont l'argent sert à financer la Sécu... Il n'y a pas de "trou", ce terme est de la pure comm pour mettre la responsabilité sur le dos du monde médical. Il y a un manque de financement, et un détournement de certains flux financiers vers d'autres postes. Et là, la cause est claire, c'est la faute de ceux qui s'occupent de ce financement).
À part ça, il ne savent pas faire grand chose correctement.
Ah si, je suis mauvaise langue, ils savent très bien lâcher les rênes des forces de l'ordre pour qu'ils cassent du manifestant et découragent la contestation par peur : pour son intégré physique (perdre un œil, une main), pour ses finances (le business de l'outrage aux forces de l'ordre, et le coût de la défense en cas de poursuites judiciaires), et finalement pour sa liberté (prison ferme pour des manifestants, en novembre 2019, plus de 1000 gilets jaunes avaient été condamnés à de la prison ferme).

**Comment by AzaleeBleue** [comment]
> Juste mon ignorance mais je me demande pourquoi ce repo existe puisque l'attestation dérogatoire est possible via : https://github.com/LAB-MI/deplacement-covid-19 non?
> 
> S'il faut faire des MAJ pour refaire un nouveau?
> 
> Merci d'avance et prenez soin de vous tous.

Je ne trouve pas de branche concernant l'attestation dérogatoire pour le confinement de novembre 2020 dans le dépôt que tu indiques. Il n'y a que des attestations de déplacement pour des cas spécifiques.

**Comment by MacKentoch** [comment]
> > Juste mon ignorance mais je me demande pourquoi ce repo existe puisque l'attestation dérogatoire est possible via : https://github.com/LAB-MI/deplacement-covid-19 non?
> > S'il faut faire des MAJ pour refaire un nouveau?
> > Merci d'avance et prenez soin de vous tous.
> 
> Je ne trouve pas de branche concernant l'attestation dérogatoire pour le confinement de novembre 2020 dans le dépôt que tu indiques. Il n'y a que des attestations de déplacement pour des cas spécifiques.

c'est supposé être ici vu le nom: `LAB-MI/attestation-deplacement-derogatoire-q4-2020`

**Comment by MacKentoch** [comment]
Mesdames Messieurs sur quoi vous basez vous pour faire des issues dans ce repo?

Il n'y a rien dans ce repo, rien ne dit que le site actuel a vraiment ses sources ici.

**SVP juste une clarification, qui a les sources? LAB_MI devrait pouvoir répondre (on doit attendre, ou c'est encore en private etc...)**

**Comment by cClaude** [comment]
> Je suppose que l'idée est: Une attestion = un repo.

Trop compliqué comme méthode, il faut faire un repo à chaque modification, c'est beaucoup plus simple à gérer... :)

Mais globalement la question est [où est le code](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/5) ?

**Comment by Apoptoz** [comment]
Dans la console de développeur, puis dans l'onglet Debugger (firefox) / Sources (chrome / brave / autres chromiums ), vous avez le code. Notamment src/js/pdf-util.js qui décrit la génération du pdf.

**Comment by patheticcockroach** [comment]
> Mais globalement la question est [où est le code](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/5) ?

Il est confiné

> Mesdames Messieurs sur quoi vous basez vous pour faire des issues dans ce repo?

Le lien en bas de la page https://media.interieur.gouv.fr/deplacement-covid-19/ (qui dit "Le code source de ce service est consultable sur GitHub.")

**Comment by LucasBourgeois** [comment]
@AzaleeBleue ok big brain.
![image](https://user-images.githubusercontent.com/18696528/97678849-c22ad100-1a94-11eb-8010-1848977af5a2.png)

**Comment by MacKentoch** [comment]
Ok le source est là, et l'explication est bien : ce repo pour le confinement de Q4 2020.

J'espère ne plus voir d'autre repo genre Qn 2021...

**Je close l'issue**
