### ISSUE TITLE
Ne fonctionne pas sur Safari (macOS)

### ISSUE THREAD

**Issue by BP22190** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#107]
...

**Comment by maximebochon** [comment]
Bonjour, c'est en effet très gênant.

Pour aider au diagnostique, pouvez-vous préciser :
- la version exacte du navigateur Safari utilisé
- la version exacte du système macOS utilisé
- la langue de fonctionnement du système (la langue dans laquelle s'affichent les menus)

**Comment by a2br** [comment]
https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/54 :)

**Comment by BP22190** [comment]
@maximebochon 

Safari : 14.0 (le dernier)
macOS : Catalina 10.15.7 (le dernier)
langue : français

Une configuration rien de plus normale quoi... ;-)

**Comment by maximebochon** [comment]
@BP22190
Le problème semble exister pour d'autres utilisateurs, comme on peut le voir ici : https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/54

La tradition étant de centraliser les demandes similaires au niveau de la demande la plus ancienne, vous pouvez vous rendre sur le lien précédent, décrire à nouveau votre problème et votre configuration, et vous devriez être notifié(e) de l'évolution du traitement du problème.

**Comment by BP22190** [comment]
Non, je ne vais pas redécrire mon problème, qui est le problème de TOUS les utilisateurs de Safari !
Vous avez été tenu informé du bug, vous le corrigez ou pas, mais me le refaire formuler, ça rime à quoi !
Je vous rappelle qu'il a déjà été notifié avec la version du printemps, sans résultat.
La véritable question donc, c'est de savoir si vous êtes en mesure de corriger ce bug ou pas.
J'ai l'impression d'être au service après-vente d'un opérateur téléphonique là...
Cordialement,

**Comment by a2br** [comment]
Magnifique état d'esprit, mais laissez-moi vous rappeler que vous n'êtes *pas* au SAV d'un opérateur téléphonique. Comme vous l'avez dit, nous sommes tous informés du bug, vous aviez donc deux solutions : dire que vous aviez le même problème dans l'issue attitrée, ou vous taire en sachant que nous étions déjà informés. C'est comme ça que les GitHub Issues marchent et ont toujours marché. Merci donc de fermer cette issue inutile. Vous avez le droit de ne pas le savoir, mais faites au moins preuve de bonne foi une fois averti, voyons.

Je n'arrive même pas à comprendre pourquoi vous perdez votre temps à refuser de respecter les normes alors qu'un copier-coller suffirait.

Édit: Ce message supprimé, quelle bravoure. Quand on est malpoli, on s'excuse, on ne fait pas comme si on avait rien dit.
