### ISSUE TITLE
Erreur 404 sur le Service Worker

### ISSUE THREAD

**Issue by sysadminstory** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#114]
Le service Worker n'est plus chargé à cause d'une erreur 404 :

Firefox : [SW ERROR] TypeError: ServiceWorker script at https://media.interieur.gouv.fr/sw.js for scope https://media.interieur.gouv.fr/ encountered an error during installation.

Chrome : [SW ERROR] TypeError: Failed to register a ServiceWorker for scope ('https://media.interieur.gouv.fr/') with script ('https://media.interieur.gouv.fr/sw.js'): A bad HTTP response code (404) was received when fetching the script.

Je suppose que l'erreur provient du changement dans ce commit : 4773bbbf044ddd87efc2a02f1a470bcc760bb318

Testé sous Firefox 82.0.2 (64 bits) & Chrome Version 86.0.4240.183 (Build officiel) (64 bits)

**Comment by theblackhole** [comment]
C'est l'inverse le commit 4773bbb (de la PR #93) corrige cette erreur ;) C'est juste que ce n'est pas encore en prod (comme indiqué dans le footer c'est la 1.0.4 en prod actuellement. on ne sait pas à quel commit ça correspond, mais en tout car il y a eu un commit 1.0.5 0ab3aad98c8e1dd589dfffc9099563f271847a42 entre temps)
