### ISSUE TITLE
https://attestation-facile.site/

### ISSUE THREAD

**Issue by eregnier** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#122]
Bonjour,

Pour information, j'ai fait [ce site](https://attestation-facile.site/) en reprennant le systeme de génération de formualaires.

j'ai mis l'accent sur la facilité a refaire de nouvelles attestations sans tout resaisir.

Le code source est ici https://github.com/eregnier/attestation-facile.site si ca intéresse quelqu'un.

Bonne journée.

**Comment by abdoulsn** [comment]
Top
Quand on passe via l'App tousanticovid. L'App intègre la même option. On ressaisie que le motif et l'heure.

**Comment by mistraloz** [comment]
Étrange de ne pas avoir repris le formulaire officiel ? C'était vraiment plus compliqué ?
https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/main/src/certificate.pdf

Dans la situation politique actuelle, je ne suis pas sur que faire preuve d'originalité soit très judicieux.

**Comment by maximebochon** [comment]
Je n'ai pas bien compris la remarque de @mistraloz sur la "situation politique", mais plus simplement on peut constater qu'au moins une faute d'orthographe a été introduite ("demerant") et que la mention du décret a disparu donc juridiquement je suppose ça pourrait nuire à l'utilisateur :

![image](https://user-images.githubusercontent.com/7842269/98239772-c4939c00-1f68-11eb-8b9a-efcc4e8806b7.png)

Quoi qu'il en soit, avec la dernière version officielle de l'attestation en ligne qui permet la mémorisation des informations saisies, et la dernière version de _TousAntiCovid_ qui facilite grandement la création de nouvelles attestations, le besoin d'alternative se fait beaucoup moins sentir.

**Comment by eregnier** [comment]
Oui je suis d'accord avec cette histoire de nouvelle version. J'ai codé mon app le weekend avant la mise a jour. Je ne cherchais pas a faire un truc parfait mais un truc utile. Je pense sue cet outil n'a plus lieu d'être. Merci pour vos remarques constructives.

**Comment by eregnier** [comment]
> Étrange de ne pas avoir repris le formulaire officiel ? C'était vraiment plus compliqué ?
> https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/main/src/certificate.pdf
> 
> Dans la situation politique actuelle, je ne suis pas sur que faire preuve d'originalité soit très judicieux.

J'ai refait le pdf de base pour voir si ca marchait facilement. Et oui la lib pdf fait bien le boulot.
Les fautes d'orthographes meriteraient d'être corrigée.
Par contre je ne suis pas certain de d'avoir une quelconque contrainte sur ce type d'outil avec " la situation actuelle". Ce projet d'attestation est open source ce qui donne envie de croire que faire ce genre d'application alternative ne pose aucun problème. Par ailleurs le systeme de l'application vient sans système de sécurité supplémentaire en terme de token de contrôle généré côté serveur et validé par les autorités, ce qui permet de ne pas mettre d'argent pour complxifier un outil qui n'a sans doute pas besoin de l'être et qui est également ethiquement très acceptable (selon moi). Un simple scan du qr code officiel permet de se rendre compte qu'il n'y a pas de magie dans tout ce système et c'est tant mieux.
