### ISSUE TITLE
QR Code - Difference avec la version en ligne?

### ISSUE THREAD

**Issue by niicojs** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#140]
Hello,

Les données du QR code de ce repo (https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/1b8d795d731b9bd02df25ef4a54708ee04068cba/src/js/pdf-util.js#L35-L43) ne sont pas les mêmes que celle du formulaire en ligne.
En particulier il y a des espaces en moins et un `;` supplémentaire à la fin de celui en ligne.

Ce code source n'est pas celui en ligne ?

Merci

**Comment by a2br** [comment]
Le code que tu as mis en ligne est censé avoir été supprimé... 🤔

**Comment by niicojs** [comment]
C'est à dire ?
Quand tu regardes ici, cette partie n'a jamais bougé : https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/commits/main/src/js/pdf-util.js

Le code qu'il faudrait pour générer un QR code identique à celui en ligne est celui la :
```
  const data = [
    `Cree le: ${creationDate} a ${creationHour}`,
    `Nom: ${lastname}`,
    `Prenom: ${firstname}`,
    `Naissance: ${birthday} a ${placeofbirth}`,
    `Adresse: ${address} ${zipcode} ${city}`,
    `Sortie: ${datesortie} a ${heuresortie}`,
    `Motifs: ${reasons}`,
    ''
  ].join(';\n');
```

**Comment by a2br** [comment]
Oui, une PR avait été faite à ce sujet. Il me semblait qu'elle avait été acceptée, je ne suis plus sûr maintenant.

**Comment by niicojs** [comment]
Bien vu c'est le #87.
Ils ont du le modifier dans leur git, mais pas le dupliquer ici.

**Comment by maximebochon** [comment]
On pourrait imaginer une moulinette qui comparerait à intervalle régulier l'écart entre les sources publiques et le code en production. Pas inintéressant comme sujet.

À noter que le nom de certains fichiers en production est "infixé" par ce qui ressemble à un identifiant unique court. Par exemple `certificate.pdf` devient `certificate.1e3570bc.pdf`, `MIN_Interieur_RVB.svg` devient `MIN_Interieur_RVB.124e26ea.svg`, etc.

**Comment by Aeris1One** [comment]
Ce serait pas les 8 premiers caractères du sha1 du fichier ou du commit correspondant ?

**Comment by mycaule** [comment]
Il semble y avoir un bot ou un admin qui merge les PR sur leur dépot (et pas systématiquement ici) en effet @betalabmi.

**Comment by maximebochon** [comment]
@Aeris1One Après analyse, le nommage "infixé" de certains fichiers en production semble venir de [_Parcel_](https://parceljs.org/) qui ajoute un condensat court avant l'extension du fichier afin d'optimiser la gestion du cache. C'est brièvement expliqué [dans la documentation de _Parcel_](https://parceljs.org/production.html#file-naming-strategy).

**Comment by niicojs** [comment]
Corrigé même si on n'a eu aucune réponse ici et aucun retour sur la PR...
