### ISSUE TITLE
Impossible de generer le formulaire. OU EST LA VERSION STATIQUE ?

### ISSUE THREAD

**Issue by epoch1970** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#146]
Safari OSX 10.13.
J'ai eu le problème de date au format US qui m'a amené ici.
Et une fois que tous les champs sont cochés le bouton de génération du PDF ne fait rien.

La mention "mon téléphone se souvient de moi" ne fait aucun sens.

Si vous n'êtes pas en mesure de faire une page de formulaire qui fonctionne, mettez en ligne un PDF.
Ca n'a pas si mal marché la dernière fois.

**Comment by maximebochon** [comment]
@epoch1970 Est-ce que vous faites référence à [ce PDF](https://www.interieur.gouv.fr/content/download/124831/999556/file/30-10-2020-attestation-de-deplacement-derogatoire.pdf#xtor=AD-322) dont le lien est fourni sur [cette page](https://www.service-public.fr/particuliers/vosdroits/R57403) ? Il y a également [cette page](https://www.gouvernement.fr/info-coronavirus/ressources-a-partager) qui décline une version PDF, DOCX et TXT.

Concernant la mention "mon téléphone se souvient de moi", la formulation est assez inédite en effet, mais ce qui m'embête le plus c'est le mot "téléphone", d'où l'_issue_ #128 et la _pull request_ #127.

Mais j'imagine que le cas d'usage standard de ce générateur d'attestation est l'exécution et le stockage sur un appareil mobile sans impression papier, d'où le QR-Code qui facilite la lecture pour les forces de l'ordre. Je vois mal pourquoi on utiliserait ce service depuis un ordinateur fixe.

**Comment by epoch1970** [comment]
Super. Je suis arrivé sur votre formulaire via el goog, sans chercher ailleurs. 
 - Peut-être répéter le lien, pour ceux qui rencontrent des difficultés?
 - Je suis bel et bien sur un desktop, ni google ni votre page ne se sont embarassés du détail. Il est possible que votre auditoire soit plus large que vous ne pensez

Merci pour la réponse rapide en tout cas.
