### ISSUE TITLE
Disponibilité du code la version du 28/11 

### ISSUE THREAD

**Issue by jccazeaux** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#162]
Bonjour,
Il semblerait que le code de la dernière version déployée cette nuit ne soit pas disponible ici, c'est normal?

Merci :)

**Comment by akididou** [comment]
J'ajouterai que le champ achat et culture semble avoir une faute de frappe puisqu'il est : "achat_culturel_culturel"

**Comment by cglacet** [comment]
C'est un autre dépôt qui est utilisé maintenant ?

**Comment by akididou** [comment]
> C'est un autre dépôt qui est utilisé maintenant ?

Je ne pense pas mais l'attestation en ligne a été MAJ : 
https://media.interieur.gouv.fr/deplacement-covid-19

**Comment by cglacet** [comment]
Le dernier commit ici remonte à 16 jours donc ce dépôt n'est pas la source de cette nouvelle version. La version courante génère ce genre de doc : 

<img width="747" alt="Screenshot 2020-11-28 at 11 58 19" src="https://user-images.githubusercontent.com/28622118/100513922-03d09980-3171-11eb-903a-bd37e0c2676d.png">

Version courante [v1.1.0](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/releases/tag/v1.1.0). Le pdf utilisé est [celui ci](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/ba233b886137da9154371af990268153cc71b96a/src/certificate.pdf).

D'ailleurs en bas de la page officielle il y a bien écrit `2020 - 1.1.0`.

**Comment by cglacet** [comment]
Je connais assez mal github, je ne trouve pas la pipeline de déploiement. Peut être qu'il y a deux URL publique, une avec cette version et une avec l'autre qu'on ne trouve pas?

**EDIT**, ah, [trouvé]( https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/actions), mais il n'y a rien, étrange.

**Comment by cglacet** [comment]
Mon intuition c'est que le code est hébergé directement sur Heroku, de souvenir c'est là qu'ils publient le code. Ils ont sûrement oublié de merge ici.

**Comment by akididou** [comment]
Effectivement github propose des solutions pour mettre en place des CI et faire du deploy automatique. Néanmoins ici github ne sert uniquement à mettre a disposition le code pour des personnes souhaitant fork le code.

Attendons qu'ils mettent à jour le repos. Sinon en attendant vous pouvez toujours changer les champs générés dans le QR code pour être à jour ;) 

Fichier qui contient les valeurs du type de sortie autorisée : 
`src/form-data.json`

**Comment by cglacet** [comment]
Oui donc il y a bien un deuxième dépôt, sur heroku. Je ne sais même pas si il est public. Je vais chercher.

**Comment by ValentinH** [comment]
> J'ajouterai que le champ achat et culture semble avoir une faute de frappe puisqu'il est : "achat_culturel_culturel"

Je vois "achats_culturel_cultuel" perso. Ca me semblait bizarre au début mais j'ai en fait appris un nouveau mot "cultuel" 😅

**Comment by ValentinH** [comment]
Je viens de mettre à jour mon fork de ce projet et en particulier le code de génération du PDF du fichier `pdp-utils.js`.

Je le met ici pour ceux que ca intéresse:
```js
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

import { generateQR } from './util'

const ys = {
  travail: 553,
  achats_culturel_cultuel: 482,
  sante: 434,
  famille: 410,
  handicap: 373,
  sport_animaux: 349,
  convocation: 276,
  missions: 252,
  enfants: 228,
}

export async function generatePdf(profile, reasons, pdfBase) {
  const creationInstant = new Date()
  const creationDate = creationInstant.toLocaleDateString('fr-FR')
  const creationHour = creationInstant
    .toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })
    .replace(':', 'h')

  const {
    lastname,
    firstname,
    birthday,
    placeofbirth,
    address,
    zipcode,
    city,
    datesortie,
    heuresortie,
  } = profile

  const data = [
    `Cree le: ${creationDate} a ${creationHour}`,
    `Nom: ${lastname}`,
    `Prenom: ${firstname}`,
    `Naissance: ${birthday} a ${placeofbirth}`,
    `Adresse: ${address} ${zipcode} ${city}`,
    `Sortie: ${datesortie} a ${heuresortie}`,
    `Motifs: ${reasons}`,
    '', // Pour ajouter un ; aussi au dernier élément
  ].join(';\n')

  const existingPdfBytes = await fetch(pdfBase).then((res) => res.arrayBuffer())

  const pdfDoc = await PDFDocument.load(existingPdfBytes)

  // set pdf metadata
  pdfDoc.setTitle('COVID-19 - Déclaration de déplacement')
  pdfDoc.setSubject('Attestation de déplacement dérogatoire')
  pdfDoc.setKeywords([
    'covid19',
    'covid-19',
    'attestation',
    'déclaration',
    'déplacement',
    'officielle',
    'gouvernement',
  ])
  pdfDoc.setProducer('DNUM/SDIT')
  pdfDoc.setCreator('')
  pdfDoc.setAuthor("Ministère de l'intérieur")

  const page1 = pdfDoc.getPages()[0]

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const drawText = (text, x, y, size = 11) => {
    page1.drawText(text, { x, y, size, font })
  }

  drawText(`${firstname} ${lastname}`, 92, 702)
  drawText(birthday, 92, 684)
  drawText(placeofbirth, 214, 684)
  drawText(`${address} ${zipcode} ${city}`, 104, 665)

  reasons.split(', ').forEach((reason) => {
    drawText('x', 47, ys[reason], 12)
  })

  let locationSize = getIdealFontSize(font, profile.city, 83, 7, 11)

  if (!locationSize) {
    alert(
      'Le nom de la ville risque de ne pas être affiché correctement en raison de sa longueur. ' +
        'Essayez d\'utiliser des abréviations ("Saint" en "St." par exemple) quand cela est possible.'
    )
    locationSize = 7
  }

  drawText(profile.city, 78, 76, locationSize)
  drawText(`${profile.datesortie}`, 63, 58, 11)
  drawText(`${profile.heuresortie}`, 227, 58, 11)

  // const shortCreationDate = `${creationDate.split('/')[0]}/${
  //   creationDate.split('/')[1]
  // }`
  // drawText(shortCreationDate, 314, 189, locationSize)

  // // Date création
  // drawText('Date de création:', 479, 130, 6)
  // drawText(`${creationDate} à ${creationHour}`, 470, 124, 6)

  const qrTitle1 = 'QR-code contenant les informations '
  const qrTitle2 = 'de votre attestation numérique'

  const generatedQR = await generateQR(data)

  const qrImage = await pdfDoc.embedPng(generatedQR)

  page1.drawText(`${qrTitle1}\n${qrTitle2}`, {
    x: 440,
    y: 130,
    size: 6,
    font,
    lineHeight: 10,
    color: rgb(1, 1, 1),
  })

  page1.drawImage(qrImage, {
    x: page1.getWidth() - 156,
    y: 25,
    width: 92,
    height: 92,
  })

  pdfDoc.addPage()
  const page2 = pdfDoc.getPages()[1]
  page2.drawText(qrTitle1 + qrTitle2, {
    x: 50,
    y: page2.getHeight() - 70,
    size: 11,
    font,
    color: rgb(1, 1, 1),
  })
  page2.drawImage(qrImage, {
    x: 50,
    y: page2.getHeight() - 390,
    width: 300,
    height: 300,
  })

  const pdfBytes = await pdfDoc.save()

  return new Blob([pdfBytes], { type: 'application/pdf' })
}

function getIdealFontSize(font, text, maxWidth, minSize, defaultSize) {
  let currentSize = defaultSize
  let textWidth = font.widthOfTextAtSize(text, defaultSize)

  while (textWidth > maxWidth && currentSize > minSize) {
    textWidth = font.widthOfTextAtSize(text, --currentSize)
  }

  return textWidth > maxWidth ? null : currentSize
}
```


Il utilise le nouveau template du PDF présent ici: https://media.interieur.gouv.fr/deplacement-covid-19/certificate.0eed39bb.pdf

**Comment by cglacet** [comment]
Haha j'ai fait ça a la main aussi, j'ai du mettre 10min a mesurer les positions, si j'avais su j'aurais attendu :p

**Comment by ValentinH** [comment]
J'ai eu la flemme de mesurer à la main, j'ai pris le code minifié du site et j'ai retrouvé les parties utiles 😄

**Comment by RJVB** [comment]
> fichier `pdp-utils.js`.

Une version 11 au moins, j'espère? ;)

Je présume que ce ne sera que lundi qu'on verra la dernière version ici (en attendant la question est à quel point l'utilisation de l'ancienne attestation pourra permettre à l'état de renflouer un peu les caisses O:-) )

**Comment by ValentinH** [comment]
La seule chose qui change de le QR code, c'est le motif "achats" remplacé par "achats_culturel_cultuel" donc je ne pense pas que ce soit une cause d'amende (je suis peut-être natif).

**Comment by RJVB** [comment]
>La seule chose qui change de le QR code, c'est le motif "achats" remplacé par "achats_culturel_cultuel" donc je ne pense pas que ce soit une cause d'amende (je suis peut-être natif).

Ça c'est peut être un peu trop subtile pour être remarqué lors d'un contrôle. Je pensais à la durée et distance ... si tu dépasses les 60 minutes et/ou 1000m de l'ancienne attestation que tu portes sur toi. En principe tu t'engages bien à ce qui est écrit sur le document que tu as signé ;)

**Comment by ValentinH** [comment]
Oui mais normalement, seul le QR code est utilisé pour les contrôles.

**Comment by jccazeaux** [comment]
On aura sûrement le merge lundi. Qui n'est jamais parti en weekend sans oublier le merge ou le push ? 🙄😁

**Comment by amezioud** [comment]
@ValentinH j'ai mis ton code dans une image docker quand je charge le site j'ai un tracker bloqué par mon navigateur:

googletagmanager.com

Le js est dans ce fichier : 
https://github.com/ValentinH/attestation-confinement/blob/main/src/pages/_document.tsx

Pas très cool non ? Quel est l'intérêt ?

**Comment by RJVB** [comment]
Peut être ça vient simplement du code exemple/modèle qu'il a adapté?

Pour moi ça montre bien un souci potentiel avec la technologie utilisée ici (nodejs); il y a tellement de dépendances qui sont chargées de façon plus ou moins automatique, et l'environnement d'execution est tellement complexe qu'il devient quasi impossible de vérifier tout ce qui se passe.

**Comment by amezioud** [comment]
Dans l'application que tu as forke je n'avais aucun tracker.

**Comment by amezioud** [comment]
![20201129_190242](https://user-images.githubusercontent.com/10462271/100549808-7e82dd00-3275-11eb-916f-19d160c7a14b.jpg)

**Comment by ValentinH** [comment]
> @ValentinH j'ai mis ton code dans une image docker quand je charge le site j'ai un tracker bloqué par mon navigateur:
> 
> googletagmanager.com
> 
> Le js est dans ce fichier : 
> https://github.com/ValentinH/attestation-confinement/blob/main/src/pages/_document.tsx
> 
> Pas très cool non ? Quel est l'intérêt ?

L'intérêt : avoir une idée du nombre de personnes utilisant mon application. Seules les pages vues sont comptées, pas d'autres informations.

Après, je ne suis pas sûr de comprendre pourquoi tu viens m'afficher sur cette issue alors que je n'ai même pas partagé mon appli ici. J'ai juste partagé le code de génération du PDF pour être sympa avec les autres personnes ayant fork le projet.

**Comment by jccazeaux** [comment]
Ca dévie de l'issue initiale...

**Comment by cglacet** [comment]
@ValentinH  tu as des compteurs bien moins invasifs si nécessaire. Exemple avec [celui ci ](https://countapi.xyz/), avec ce genre d'api tu as un contrôle absolu sur ce que tu décide de partager. Après le mieux c'est d'etre transparent dessus, tant que les utilisateurs savent a quoi s'attendre tout va bien. Des trackers il y en a sur tous les sites qu'on visite quotidiennement. Ceci dit si le but est simplement de compter autant prendre un service qui ne fait que ça, comme ça c'est clair pour l'utilisateur connaisseur que tu ne fais effectivement rien de plus.

**Comment by ValentinH** [comment]
Merci pour ces infos.
Je n'ai pas de problème pour en discuter mais je ne comprends pourquoi on parle de ça sur cette issue. Mon code est open-source, si quelqu'un a des questions ou suggestions, il suffit de créer une issue là-bas.

**Comment by RJVB** [comment]
>Ca dévie de l'issue initiale...

Effectivement!

Grace à @ValentinH on a maintenant ce qu'il faut pour générer un pdf quasi 100% correct. Est-ce qu'il y a une manière de mettre les autres fichiers à jour également à partir du site officiel?

**Comment by RJVB** [comment]
Edit: fixed in e7efba9
