### ISSUE TITLE
Le site provoque une barre de défilement horizontal sur mobile

### ISSUE THREAD

**Issue by hteumeuleu** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#19]
Sur mobile, ou sur toute fenêtre d'une largeur inférieur à 464px, le site provoque une barre de défilement horizontal dans le navigateur. Problème reproduit dans Firefox 83 sur macOS 10.14.6, dans Safari sur iOS 14.0 et dans Chrome 86 sur Android 10.

**Exemple dans Firefox 83 sur macOS 10.14.6**

[![Capture d'écran dans Firefox](https://i.imgur.com/KlU96mdm.png)](https://i.imgur.com/KlU96md.png)

C'est dû aux styles appliqués sur la balise `<fieldset id="reason-fieldset" class="fieldset">` : 

```
.fieldset {
  margin-left: -2em;
  margin-right: -2em;
  padding-left: 2em;
  padding-right: 2em;
  border: 3px solid transparent;
}
```

Le décalage de `-2em` fait sortir le site du cadre de la zone visible. Sur le `<body>`, on a un `padding:20px`. En reprenant cette valeur de 20px, on évite le défilement horizontal sur mobile.

```
.fieldset {
  margin-left: -20px;
  margin-right: -20px;
  padding-left: 20px;
  padding-right: 20px;
  border: 3px solid transparent;
}
```

À noter qu'idéalement il serait préférable d'utiliser des unités relatives partout (`em` ou `rem`). On peut alors remplacer la valeur `20px` ici par `1.25rem` (aussi bien sur le `.fieldset` que sur le `body`).

**Comment by betalabmi** [comment]
Merci beaucoup !

**Comment by hteumeuleu** [comment]
Je confirme que c'est corrigé. Merci !
