### ISSUE TITLE
Erreur à corriger

### ISSUE THREAD

**Issue by JulHug** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#2]
Dernier choix du générateur : `Déplacement pour chercher les enfants à l’écoles `
Il faut supprimer le pluriel à "école".
Julien HUGELÉ

**Comment by MacKentoch** [comment]
Le repo est vide 😮 ou c'est moi?

Le premier ministre a dit si je ne me trompe pas que c'est l'école qui fournira des attestations dans ce cas.
Au feeling pas dans ce générateur plus généraliste?

**Comment by Mellewanadoo** [comment]
> Le repo est vide 😮 ou c'est moi?
> 
> Le premier ministre a dit si je ne me trompe pas que c'est l'école qui fournira des attestations dans ce cas.
> Au feeling pas dans ce générateur plus généraliste?

Je pense que c’est le temps que les écoles remplissent les et tamponnent toutes les attestations permanentes.
