### ISSUE TITLE
erreur dernière proposition école avec "s" et manque la creche

### ISSUE THREAD

**Issue by Gerard64990** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#21]
See title

**Comment by Alomon31** [comment]
Et il manque les assistantes maternelles également.

**Comment by edoigtrd** [comment]
Ce code est le code du générateur d'attestation pas du document
En effet l'attestation générée se base sur le modèle fournit par le gouvernement
Si vous souhaitiez des modifications sur ce document c'est le gouvernement qu'il faut contacter et non les développeurs du générateur
