### ISSUE TITLE
Les sources du dépôt ne sont pas accessibles au public

### ISSUE THREAD

**Issue by FabienZa** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#23]
Contrairement à ce qui est précisé sur le site :  
![image](https://user-images.githubusercontent.com/38133819/97679116-20f04a80-1a95-11eb-922f-d30e64c4fb28.png)

**Comment by patheticcockroach** [comment]
#5

**Comment by FabienZa** [comment]
Sources ajoutées
