### ISSUE TITLE
Épidémie de LA covid

### ISSUE THREAD

**Issue by ptaillard** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#25]
Même si je n'arrive toujours pas à m'y faire 😊, il faut dire "l'épidémie de la covid" au lieu "l'épidémie de covid" comme c'est le cas dans l'attestation

**Comment by patheticcockroach** [comment]
> il faut dire "l'épidémie de la covid" au lieu "l'épidémie de covid"

Comme dans la bien connue "épidémie de la grippe" ?
