### ISSUE TITLE
Un seul motif par attestation ?

### ISSUE THREAD

**Issue by nicolinuxfr** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#26]
L'attestation papier indique qu'il faut choisir un seul motif, la version numérique aussi… mais on peut en sélectionner plusieurs.

Est-ce une erreur de la version numérique ou des textes explicatifs ? Faut-il se tenir à un seul motif ou peut-on/doit-on en saisir plusieurs quand cela s'applique à une même sortie ?

**Comment by pierregoutagny** [comment]
@nicolinuxfr De quel texte explicatif parlez-vous ? Je suis d'accord que le PDF de l'attestation utilise le singulier (donc qu'on ne peut y cocher qu'une seule case), mais je ne trouve pas de texte explicatif qui propose de choisir plusieurs motifs.
Cependant, comme il est possible de cocher plusieurs cases avec un stylo sur une version imprimée, je trouve normal qu'on puisse cocher plusieurs cases avec la version informatisée...

**Comment by nicolinuxfr** [comment]
Je parlais des textes sur les attestations elles-mêmes. Mais j'ai vu que l'on pouvait avoir plusieurs motifs ici : https://www.service-public.fr/particuliers/actualites/A14376, donc c'est bon, j'ai ma réponse. :-)
