### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Mirrdhyn** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#28]
https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/bdad4c95c284ba8851e503a9d3bc4774f7ff4856/package.json#L3

La version sur le site officiel et le code ci-avant ne correspondent pas.

Site officiel : 1.0.6-e38dfbf
Code source : 1.0.3

**Comment by betalabmi** [comment]
Oui, c'est corrigé
