### ISSUE TITLE
lien de reférence [*] ne fonctionne pas

### ISSUE THREAD

**Issue by abdoulsn** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#3]
Le click sur les liens de références ne redrige pas en bas de page.

**Comment by MarOwNFR** [comment]
Bonjour,

Pour moi tout fonctionne, merci de spécifier l'appareil utilisé, le navigateur et sa version s'il vous plaît.

Cordialement.

**Comment by abdoulsn** [comment]
Ca marche pas, je parle des liens dans les crochets [].
Sur mon Ubuntu avec Firefox -V 82.0 et safari ios 14.1

**Comment by MarOwNFR** [comment]
Je sais très bien se qu'es un lien de référence, merci... Et je vous confirme que cela est fonctionnel sur chromium sur Windows... Lors du clic sur un lien de référence, la page descend et se positionne au niveau de la référence sélectionnée...

**Comment by MarOwNFR** [comment]
Firefox également d'ailleurs...

**Comment by abdoulsn** [comment]
Pour moi non. regardez.
https://mega.nz/file/nVs0Ha6T#zd7fzQrkERx0u6P2NT-bvN5H926-OE7w663Sk4DOhr0

**Comment by pierregoutagny** [comment]
Ca ne fonctionne pas avec Firefox 82.0.2, ni Chrome 86.0.4240.111 sous Arch. Plus précisément, cliquer sur ces liens scroll de sorte à ce que ces liens soient en haut de la page (cf vidéo précédente). On est donc redirigé vers le lien sur lequel on vient de cliquer...

C'est à mon avis un bug dû à un non-respect du standard HTML :
On a `<a class="footnote" id="footnote1" href="#footnote1">[1]</a>`, puis `<span id="footnote1">` en bas de la page. Ce n'est pas autorisé dans le standard HTML (les id doivent être uniques), et donc laissé à la libre interprétation des navigateurs. Certains préfèreront sauter au *prochain* élément qui a l'id auquel on fait référence, donc ici la footnote; d'autres (c'est mon cas et celui d'OP, visiblement), sautent au *premier* élément qui a l'id, donc ici le lien sur lequel on vient de cliquer.
**Solution : ne pas donner au lien le même id que l'élément auquel il renvoie.**

**Comment by abdoulsn** [comment]
Résolu, merci :).
