### ISSUE TITLE
Nomenclature de Branche

### ISSUE THREAD

**Issue by didieraupest** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#34]
La branche par défaut du dépôt se nomme `master`.
Or, selon les dernières guidelines de GitHub, la branche par défaut devrait se nommer `main`.

Source: https://github.com/github/renaming

A priori, tous les nouveaux dépôts sont déjà censés appliquer cette règle, comment se fait-il que ce dépôt, créé il y a peu, ne respecte pas les guidelines ?

**Comment by a2br** [comment]
La nomenclature par défaut est toujours `master`, il me semble. Néanmoins, dans les guides rapides pour associer un projet à un repo GitHub, parmi les instructions il y a bien `git branch master -M main`.

**Comment by bastantoine** [comment]
@didieraupest effectivement ce changement a été mis en place récemment. À ma connaissance, pour l'instant uniquement GitHub l'a mis en place. Ainsi si le repo a d'abord été créé avec un `git init`, (ce qui a été le cas je pense) la branche par défaut est toujours `master`. Par ailleurs il est toujours possible de revenir à l'ancien comportement en changeant une option dans ses préférences GitHub.

**Comment by betalabmi** [comment]
Bonjour, merci pour votre participation. Tout ce qui a été dit est très juste.

Le changement du nom de la branche par défaut est en cours (il faut éventuellement attendre les fusions de PR existantes avant de pouvoir supprimer la branche `master`).

**Comment by SasquatchYuja** [comment]
Selon les conventions par [défaut](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#_your_default_branch_name) de Git, conserver le nommage par défaut est à mon sens préférable aux guidelines de Github, les différentes sources des outils du Gouvernement liés au Covid19 étant dispersés entre différents hôtes (Github, Gitlab...), c'est d'autant plus indiqué de suivre les conventions de Git, non ?

**Comment by bastantoine** [comment]
@SasquatchYuja je suis d'accord avec ce point, d'autant plus que seul GitHub a effectué ce changement, pour l'instant du moins.

**Comment by SasquatchYuja** [comment]
Ceci étant dit, le terrain est assez glissant. Je doute que le fond du problème soit le respect de telle ou telle convention. Il est surtout question du débat clivant master-slave-(white|black)list-kill sur lequel chacun a en général un avis intangible.

**Comment by didieraupest** [comment]
En dehors du débat `master` | `main`, c'est potentiellement qu'il manque un fichier CONTRIBUTING qui définit les guidelines.
Aujourd'hui, sur github.com, le format par défaut pour un nouveau dépôt est d'utiliser `main`. Ca me semble plus cohérent de s'appuyer sur les guidelines de l'outil sur lequel le code est publié, si il n'y a pas de mentions contraires.

Ce dépôt s'appuie sur le depôt précédent https://github.com/LAB-MI/deplacement-covid-19, sans pour autant reprendre l'historique de ce dernier.
Si c'est pour faire table rase de ce qui a déjà été fait, pour donner un coup de frais, pourquoi pas. Mais, autant appliquer les guidelines actuelles de l'outil je pense.
