### ISSUE TITLE
Complétion motif familial imperieux

### ISSUE THREAD

**Issue by ychergui-zz** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#35]
Bonjour,

Pouvez-vous mettre à jour la ligne concernant le motif familial impérieux en accord avec l'article 4 du décret n° 2020-1310 du 29 octobre 2020 pour ajouter les déménagements ?

Source : https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000042475180

Merci

**Comment by pierregoutagny** [comment]
Je suis d'avis de ne changer le texte du générateur que lorsque le texte du PDF sur lequel il se base aura changé. Pour l'instant, la version téléchargeable sur le [site du ministère](https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestations-de-deplacement) ne reflète pas l'article que vous citez, donc le générateur non plus...

**Comment by ychergui-zz** [comment]
Je suis d'accord, si le texte du générateur est basé sur le PDF du ministère alors ce dernier sera à mettre à jour quand le premier le sera.

Merci pour votre réponse.
