### ISSUE TITLE
Option manquante: Deplacement entre un aeroport/gare et lieu de domicile

### ISSUE THREAD

**Issue by psyycker** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#40]
Je vais rentrer en France depuis l'Angleterre tres bientot et je dois me munir de cette autorisation. Probleme etant qu'il n'y a aucune option correspondant au fait que je doive transiter entre l'aeroport et chez moi et aussi aucune option pour le membre de ma famille venant me recuperer.

**Comment by EmileCalixte** [comment]
Ce projet ne permet que de générer une attestation numérique par rapport au modèle de document fourni par le gouvernement : https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestations-de-deplacement

**Comment by FabienZa** [comment]
Je crois que dans ce cas il faut une attestation sur l'honneur expliquant le motif du déplacement pour toi et ton proche.

**Comment by psyycker** [comment]
Je vois. Dans ce cas, peut etre que ce serait un ajout sympa d'avoir un lien vers cette attestation si aucune des options ne convient!

**Comment by betalabmi** [comment]
Bonjour, ce n'est pas l'objet de ce projet

**Comment by psyycker** [comment]
Je pense que l'objet de ce projet est d'assister un maximum les Français dans cette periode difficile et l'acces a l'information est, pour ainsi dire, mediocre. Si tous les sites pouvaient se relier les uns aux autre, ce genre d'issue n'apparaitrait meme pas. Vous devriez peut etre reconsiderer cette reponse.

**Comment by SasquatchYuja** [comment]
@betalabmi 
> Bonjour, ce n'est pas l'objet de ce projet

Notez que le readme référence déjà (à raison) les versions précédentes [ICI](https://github.com/nesk/covid-19-certificate) et [LA](https://github.com/LAB-MI/deplacement-covid-19) à l'exception (à tord) de celle pour le [couvre-feu](https://github.com/LAB-MI/attestation-couvre-feu-covid-19) et du [site de génération en ligne](https://media.interieur.gouv.fr/deplacement-covid-19).

Faire les choses à moitié risque de perturber plus qu'autre chose, et de rendre plus difficile la compréhension de l'historique de développement, comme c'est déjà le cas lorsque l'on regarde les PRs et issues encore créées sur des repos censés être morts à ce jour.

Je vous propose donc :
- D'ajouter les deux liens suivants dans le paragraphe du readme qui y est déja dédié :
  1. [couvre-feu](https://github.com/LAB-MI/attestation-couvre-feu-covid-19), le dernier repo en date avant le repo actuel
  2. le [site de génération en ligne](https://media.interieur.gouv.fr/deplacement-covid-19)
- D'archiver les trois repos cités précédemment et d'indiquer clairement dans leur readme à quel(s) dépôts se référer

Par ailleurs, il serait (très) peu coûteux, et tout à fait pertinent contrairement à ce que vous dites, de mentionner la source des modèles auxquels vous indiquez vous même vous référer scrupuleusement, à savoir :
- la mention que l'application tousanticovid est un autre moyen de génération (à vérifier pour ce point, je ne l'ai pas installée)
- [ce lien](https://www.gouvernement.fr/info-coronavirus/ressources-a-partager) et [celui-ci](https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestations-de-deplacement) où il est possible de récupérer les dernières attestations à jour
