### ISSUE TITLE
What about GPRD ?

### ISSUE THREAD

**Issue by mpromonet** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#41]
Hi,

I did not see any notice explaining how the nominative data are managed according to GPRD principle.
May you clarify how it comply with it ?

Best Regards,
Michel.

**Comment by betalabmi** [comment]
Hi,

No data is stored anywhere, except the user's device.

**Comment by mpromonet** [comment]
Hi betalabmi,

Thanks for the quick response, It may be nice to explain this in the README, for instance.
It could be difficult to know if some dependencies are using or not cloud API.  
I check running the code locally, it run without network access filling the pdf.   

By the way I found in your repository the file https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/main/src/confidentialite.html give some hints and is linkend in https://media.interieur.gouv.fr/deplacement-covid-19/confidentialite.html

Best Regards,
Michel.

**Comment by pierregoutagny** [comment]
@mpromonet I just tested v1.0.4 with the Chrome network activity analyser (the "Network" tab in the Chrome dev tools), and there is no network activity after the inital loading of the page. Neither while I was typing, nor when I clicked on the "Générer une attestation" button. The only cookies that appear in the requests made while loading additional resources for the webpage seem to be the usual cookies for the governemnt's websites, of which you can find a somewhat detailed review [here](https://www.gouvernement.fr/en/personal-data-and-cookies).
I hope you find this quick analysis convincing enough.
