### ISSUE TITLE
Ajout de la possibilité de laisser les champs de notre choix vides afin de compléter manuellement

### ISSUE THREAD

**Issue by FabienZa** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#46]
Lorsque le fichier généré est utilisé au format papier, cela permet de :  
- pouvoir imprimer des attestations en avance pour nos proches (avec seulement la croix à faire, date et heure)
- compléter la date et l'heure au moment du départ (lorsque celui-ci est différé de l'impression)

**Comment by sosnut** [comment]
Ce n'est pas le but ici, le fichier généré pour l'attestation numérique comporte un code QR qui contient la date et l'heure.

Ce que vous souhaitez peut être plus facilement réalisé à l'aide de photocopies à partir de l'attestation papier https://www.interieur.gouv.fr/content/download/124831/999556/file/30-10-2020-attestation-de-deplacement-derogatoire.pdf

**Comment by FabienZa** [comment]
Ha bon d'accord.

Je pensais pourtant ça serait beaucoup plus utile de pouvoir utiliser ce générateur pour pré-remplir des attestations.

La QR Code qui ne fait que résumer ce qui est déjà juste à côté me semble moins intéressant, il suffirait d'ailleurs de laisser la date et l'heure à vide dans celui-ci, en quoi serait-ce gênant ?

**Comment by betalabmi** [comment]
Cet outil est fait pour générer une attestation numérique.
