### ISSUE TITLE
Erreur en cochant les cases

### ISSUE THREAD

**Issue by edoigtrd** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#48]
Bonjour
En générant des attestations via le site https://media.interieur.gouv.fr/deplacement-covid-19/ 
 j'ai remarqué que la croix dessinée est décalée sur la droite par rapport a la case correspondante au motif de sortie
Il me semble avoir localisé l'erreur sur la ligne 80 de la classe src/js/pdf-util.js

**Comment by theblackhole** [comment]
Je crois que l'erreur a été corrigée entre-temps car je ne vois pas de problème sur la 1.0.4 en ligne à l'heure actuelle

**Comment by edoigtrd** [comment]
Ça m'a l'air d'être bon je ferme l'issue
