### ISSUE TITLE
Repository vide

### ISSUE THREAD

**Issue by jak78** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#5]
Bonjour
Le repository est vide.
Possible de fixer ça ? Ou qqn a-t-il les sources ?
Merci

**Comment by iamhsa** [comment]
Probablement quelqu'un qui a oublié de faire un `git push` !
Ou bien des adèptes de https://github.com/kelseyhightower/nocode

**Comment by simbelmas** [comment]
De belles promesses, on commence à être habitué que ce soit vide derrière :D

**Comment by romain-banchetti** [comment]
L'attestation est a priori dispo à cette adresse : https://media.interieur.gouv.fr/deplacement-covid-19/index.html
Bien que le ministère de l'intérieur ait publié un lien vers cette adresse : https://media.interieur.gouv.fr/deplacement-covid-19/
(c.f. https://www.interieur.gouv.fr/)

**Comment by ilhan69** [comment]
> L'attestation est a priori dispo à cette adresse : https://media.interieur.gouv.fr/deplacement-covid-19/index.html
> Bien que le ministère de l'intérieur ait publié un lien vers cette adresse : https://media.interieur.gouv.fr/deplacement-covid-19/
> (c.f. https://www.interieur.gouv.fr/)

Merci de nous l’apprendre mais ces deux url reviennent au même. Lorsque l’url se termine par / c’est le fichier index qui est lu.

**Comment by pierregoutagny** [comment]
J'imagine que le code sera publié demain pendant les horaires de travail de l'équipe qui l'a écrit. Je ne sais pas s'ils font des heures sup jusqu'à 23h30 juste pour les quelques impatients de GitHub :/

**Comment by romain-banchetti** [comment]
> > L'attestation est a priori dispo à cette adresse : https://media.interieur.gouv.fr/deplacement-covid-19/index.html
> > Bien que le ministère de l'intérieur ait publié un lien vers cette adresse : https://media.interieur.gouv.fr/deplacement-covid-19/
> > (c.f. https://www.interieur.gouv.fr/)
> 
> Merci de nous l’apprendre mais ces deux url reviennent au même. Lorsque l’url se termine par / c’est le fichier index qui est lu.

Pas forcément, cela dépend de la configuration du serveur HTTP. Mais ici c'est bien le cas en effet (comme je viens de m'en rendre compte) mais j'avais manifestement du cache qui me faisait voir ceci à la place (j'ai dû faire un refresh forcé pour voir la nouvelle) : 
<img width="880" alt="Capture d’écran 2020-10-29 à 23 23 17" src="https://user-images.githubusercontent.com/34170819/97638877-ced00a80-1a3d-11eb-91a8-ed4bd3505eca.png">

**Comment by cl-parsons** [comment]
En fait tout était prévu, c'est pour examiner à quelle vitesse quelqu'un forkerait le projet pour l'écrire de son côté. Astucieux les sbires à Manu!

En dehors de ça, je vous propose de partager vos petits "tricks" pour détourner ce confinement dans les issues!

**Comment by alexduros** [comment]
Le sourceMap est dispo. Une petite recherche sur `generatePdf` devrait aider.
![Screen Shot 2020-10-30 at 09 42 55](https://user-images.githubusercontent.com/629642/97678575-55afd200-1a94-11eb-9c32-485d35298b07.png)

**Comment by cClaude** [comment]
Si le code source n’arrive pas, il faut que l’on s’organise pour cloner https://github.com/LAB-MI/deplacement-covid-19 puis l’adapter (il y a de bonne PR à prendre en plus). Je ne pense pas qu’il y ait beaucoup de travail, puisqu’il n’y a que de l’ajout de texte à faire…

**Comment by reivaxy** [comment]
> > > L'attestation est a priori dispo à cette adresse : https://media.interieur.gouv.fr/deplacement-covid-19/index.html
> > > Bien que le ministère de l'intérieur ait publié un lien vers cette adresse : https://media.interieur.gouv.fr/deplacement-covid-19/
> > > (c.f. https://www.interieur.gouv.fr/)
> > 
> > 
> > Merci de nous l’apprendre mais ces deux url reviennent au même. Lorsque l’url se termine par / c’est le fichier index qui est lu.
> 
> Pas forcément, cela dépend de la configuration du serveur HTTP. Mais ici c'est bien le cas en effet (comme je viens de m'en rendre compte) mais j'avais manifestement du cache qui me faisait voir ceci à la place (j'ai dû faire un refresh forcé pour voir la nouvelle) :
> <img alt="Capture d’écran 2020-10-29 à 23 23 17" width="880" src="https://user-images.githubusercontent.com/34170819/97638877-ced00a80-1a3d-11eb-91a8-ed4bd3505eca.png">

Quelle que soit la configuration du serveur, tu ne pourras récupérer au mieux que la version générée pour publication, pas les sources, qui devraient être ici.

**Comment by reivaxy** [comment]
> Si le code source n’arrive pas, il faut que l’on s’organise pour cloner https://github.com/LAB-MI/deplacement-covid-19 puis l’adapter (il y a de bonne PR à prendre en plus). Je ne pense pas qu’il y ait beaucoup de travail, puisqu’il n’y a que de l’ajout de texte à faire…

Pas forcément, il peut aussi y avoir la génération du pdf à modifier.

**Comment by patheticcockroach** [comment]
Woohoo, la source viens d'arriver ^^

**Comment by jak78** [comment]
Merci pour la publication du code !
