### ISSUE TITLE
La date devrait être systématique dans le format français jj/mm/aa [puisque l'attestation est destinée à des policiers français]

### ISSUE THREAD

**Issue by MagTun** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#51]
J'ai un téléphone qui est paramétré en anglais et lorsque je choisis la date pour l'attestation, elle est entrée en format anglais mois/jour/année. 

Il faut que le format de la date soit rectifié pour toujours apparaitre sous la forme jour/mois/année. 

Une attestation avec une date anglaise pourrait être jugée non valide par les policiers qui pourraient du coup mettre une amende.

**Comment by MagTun** [comment]
Rectification : il n'y a que le formulaire qui faut changer car sur l'attestation qui est téléchargée, la date est bien sous format français.

**Comment by a2br** [comment]
En effet. Les entrées de date/heure sont natives, donc dépendent de l'appareil/navigateur en question.

**Comment by sundowndev** [comment]
> Rectification : il n'y a que le formulaire qui faut changer car sur l'attestation qui est téléchargée, la date est bien sous format français.

Où est le problème alors ?

**Comment by ilhan69** [comment]
Comme l'a dit a2br les entrées de date/heure sont natives. Donc c'est ton mobile qui adapte le champs parceque tu es en "anglais" mais la partie mécanique récupère correctement les informations comme il le faut et place la date en français donc pas de problème. Eviter de créer des issues inutiles
