### ISSUE TITLE
Faute de grammaire sur le dernier motif 

### ISSUE THREAD

**Issue by ThomasGu75** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#6]
Corriger la faute sur ecole dans le texte 

Déplacement pour chercher les enfants à l’écoles et à l’occasion de leurs activités périscolaires ;

**Comment by pierregoutagny** [comment]
[Doublon](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/2)

**Comment by darmanin-ou-cedric-o** [comment]
Si on s'amuse à corriger les fautes, il faudrait aussi harmoniser les suguliers et les pluriels. Les premiers motifs sont au pluriel (déplacements), les derniers au singulier (convocation et déplacement)

On pourrait même pousser le zèle jusqu'à veiller à ce que chaque motif se termine par un point virgule ... Plutôt que d'en avoir un qui n'a droit qu'à un point

**Comment by fedaya** [comment]
À vrai dire, @darmanin-ou-cedric-o , si l'on suit les règles de typographie, il y a un seul motif qui doit se terminer par un point, et c'est le dernier!

**Comment by pierregoutagny** [comment]
Le [PDF](https://www.interieur.gouv.fr/content/download/124831/999556/file/30-10-2020-attestation-de-deplacement-derogatoire.pdf#xtor=AD-322) disponible sur le [site du ministère de l'intérieur](https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestations-de-deplacement) met un point à chacune des 6 premières options, et rien aux 3 dernières. Je ne pense pas que ce soit le rôle du générateur de faire mieux (voire autre chose) que ce que le document officiel propose...

**Comment by ThomasGu75** [comment]
Le texte est correcte dans le formulaire intégré
