### ISSUE TITLE
Problème de cache : formulaire datant du 16 octobre

### ISSUE THREAD

**Issue by clemishow** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#61]
Lorsque je me rends sur le lien https://media.interieur.gouv.fr/deplacement-covid-19/ depuis Chrome sur mon téléphone je tombe du le formulaire du 16 octobre 2020 : 
![Screenshot_20201030-163223_Chrome](https://user-images.githubusercontent.com/9325482/97726095-2e2a2b00-1acf-11eb-838e-99a567bb5195.jpg)

Si je rafraîchis la page, c'est toujours le 16 octobre. Cependant si je l'ouvre avec mon ordinateur, j'ai la date du 29 octobre.

**Comment by LucasBourgeois** [comment]
Vides ton cache dans les paramètres du navigateur de ton tel.

Peut être faut t'il rajouter un flag qui permet de déterminer si le cache doit se vider selon la version en cache comparé à la dernière version de prod 🤔

**Comment by clemishow** [comment]
Oui vider son cache c'est OK pour moi, mais pour nos utilisateurs ce n'est pas le cas, en plus c'est une webview sous Android et IOS.

**Comment by theblackhole** [comment]
Normalement une petite notification apparait en bas quand une mise à jour est disponible, ce qui force la récupération de la dernière version.

**Comment by clemishow** [comment]
![Screenshot_20201031-115854_Chrome](https://user-images.githubusercontent.com/9325482/97777470-aac11600-1b70-11eb-93de-68f5564f0ca6.jpg)
De mon côté tout en bas de la page je n'ai rien pour forcer la récupération de la dernière version.
La notification apparaît ou ?

**Comment by clemishow** [comment]
Je pense avoir résolu le problème et il venait du plugin pour les webviews qu'on utilise sur Cordova.
