### ISSUE TITLE
Remember Me - Nouvelle fonctionnalité

### ISSUE THREAD

**Issue by LucasBourgeois** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#65]
Bonjour,

Avoir une opt-in remember me serait pas mal afin d'auto remplir le formulaire plutôt que de devoir ressaisir à chaque fois les mêmes infos !

Une solution simple serait d'avoir les infos dans le localstorage (pas les cookies comme ça pas trop embêté avec les rgpd etc etc) ou autre chose de plus sécurisé ? 🤔

**Comment by theblackhole** [comment]
Plusieurs approches (localStorage, URIFragment...) sont actuellement en cours d'étude et pas mal d'issues et PR ont déja été ouvertes à ce propos : https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/projects/1#column-11475547

**Comment by LucasBourgeois** [comment]
Je close du coup ?
