### ISSUE TITLE
Un champ “Signature”, est-il utile?

### ISSUE THREAD

**Issue by ghost** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#67]
Bonjour. 
Est-ce normal qu’il y ait un champ “Signature” sur le document généré? Ce champ n’a pas été présent sur l’attestation générée lors de premier confinement. Et je vois mal comment (et pourquoi?) on voudra signer la version numérique. Le but n’est-il pas d’avoir justement la version “numérique mobile” avec Code QR??? 
Si je pose la question, c’est pour éviter de nombreuses confusions entre les usagers et les agents des forces de l’ordre qui pourront, à très juste titre, de se poser la question: “Pourquoi l’attestation n’est-elle pas signée?” (donc pas juridiquement valide...). Ne vaut-il pas mieux éviter ce genre de confusion et supprimer ce champ?
Bien cordialement.

**Comment by LucasBourgeois** [comment]
Peut être rajouter une zone pour signer simplement avec son doigt ? - sur mobile uniquement
La signature dessinée serait directement ajoutée au document généré.
La signature serai à conserver dans la solution qui sera choisie ?

**Comment by theblackhole** [comment]
Je suppose que le champ signature est simplement là car ça serait compliqué de maintenir 2 pdf à jour (un pour la version imprimable, l'autre pour la version numérique). 
Les forces de l'ordre savent qu'une attestation numérique pdf avec qr code ne peut pas être signée.
D'ailleurs, le qr fait un petit peu office de signature électronique puisqu'il contient la date et heure de génération du pdf.

**Comment by ghost** [comment]
> Je suppose que le champ signature est simplement là car ça serait compliqué de maintenir 2 pdf à jour (un pour la version imprimable, l'autre pour la version numérique).

L’attestation mars-avril générée en ligne n’avait pas de ce champ “Signature”. Donc ce n’est pas un problème de maintien de 2 pdf.

> Les forces de l'ordre savent qu'une attestation numérique pdf avec qr code ne peut pas être signée.

Tout le problème est là. Personne ne sait rien; beaucoup de textes et directives sont flous et sont laissés à l’appréciation personnelle de chacun… Donc, au lieu d’ajouter sa graine à la confusion générale, ne vaut-il pas mieux supprimer ce champ?

> D'ailleurs, le qr fait un petit peu office de signature électronique puisqu'il contient la date et heure de génération du pdf.

C’est exactement ce que j’ai dit. À quoi bon avoir un champ “signature”, si on a déjà un QR code?

**Comment by christophe-calmejane** [comment]
Est-ce que l'attestation elle même doit être présentée, ou uniquement le QR-code ?
Auquel cas, le champ signature n'a pas vraiment d'importance.

**Comment by ghost** [comment]
> Est-ce que l'attestation elle même doit être présentée, ou uniquement le QR-code ?
> Auquel cas, le champ signature n'a pas vraiment d'importance.

Très bonne question! Dans ce cas, à quoi sert toute la page avec le texte? Pourquoi ne pas générer le seul QRcode alors???

À la fin, **la question est très simple: qui gère cet outil???** Je veux dire qui décide quel texte y mettre, quels champs doivent être ajoutés ou supprimés, quelle fonctionnalité à implémenter… **Est-ce l’État** (ce dépôt semble appartenir au Ministère de l’Intérieur et tous les sites gouvernementaux renvoient vers ce code)? **Ou bien c’est un group de développeurs freelance/communautaire** (qui ont quel statut alors?)?
Le tout est de savoir **qui, en cas de litige et de non-conformité de formulaire numérique, sera juridiquement responsable**. Est-ce que quelqu’un de l’équipe officielle de ce dépôt peut y répondre? @LAB-MI @philippeBron @cristianpb

Et, puisque on y est, une question subsidiaire, mais tout aussi importante. Comment se fait-il qu’**après presque 8 mois et des milliards subventionnés** pour la gestion de cette crise, **on ne soit toujours pas capable de produire un outil pour générer une seule (sic!) page PDF** qui marche sans bugs, qui a toutes les fonctionnalités et qui n’a pas de fautes de français?

**Comment by a2br** [comment]
@andrewgr1812 Si tu tiens tant que ça à signer, je te redirige vers [ce site](https://johann.pardanaud.com/covid-19-certificate/) ([repo](https://github.com/nesk/covid-19-certificate)), qui est l'origine du générateur d'attestation dont nous parlons, il permet la signature et est d'après moi d'excellente qualité. Mets du Tipp-Ex sur le champ de signature si c'est toujours trop compliqué... L'attestation est un document officiel pensé pour être imprimé et rempli traditonnellement avec un stylo. Je comprends que cela soit frustrant et que cela n'ait aucun sens, mais ça ne vaut pas la peine de s'exciter pour si peu. Si tu n'apprécies pas le travail fait par des devs, indépendants du gouv, qui dédient leur temps libre à rendre la vie un peu plus facile au gens avec de l'open source, je peux t'assurer que GitHub n'est pas l'endroit où s'en plaindre... Ou alors, dis le poliment.

**Comment by tomchen** [comment]
@a2br
> [...] L'attestation est un document officiel pensé pour être imprimé et rempli traditonnellement avec un stylo. [...]

C'est vrai ? Je croyais que cette attestation numérique est à télécharger sur smartphone. On ouvre le ficher PDF et montre l'attestation sur l'écran smartphone lors du contrôle pour scanner le code QR... Pratiquement tout le monde fait comme ça non ?

En effet, il y a de confusion: cette attestation numérique:

1. doit être impérativement imprimée, et à signer avec un stylo.
2. pourrait être imprimée OU conservée dans le smartphone. Si imprimée, elle est à signer avec un stylo; si version PDF dans le smartphone, le fichier PDF a un champ "Signature" mais on n'a pas trop de moyen pour signer.
    1. Il faut signer.
    2. Lors du contrôle, il suffit de montrer l'attestation, avec ou sans signature. Et il y a deux questions supplémentaires (mais non importantes) : lors du contrôle, l'attestation sur smartphone doit avoir un QR code ou pas ? (je crois pas ?) et il suffit de montrer juste le QR code sans le texte ? (ummm je sais pas, peut-être "non" ?)

Ce issue est valide dans le cas 2-i, en haute priorité. Il est également valide dans le cas 2-ii mais en basse priorité, le champ "Signature" dans le formulaire est facultatif, mais pourrait être ajouté quand même. Je disais que pratiquement la situation actuelle est 2-ii.

Si le issue est valide, le formulaire pourrait ajouter un champ Signature comme son origine https://johann.pardanaud.com/covid-19-certificate/

**Comment by ghost** [comment]
> @a2br [...] ça ne vaut pas la peine de s'exciter pour si peu. Si tu n'apprécies pas le travail fait par des devs, indépendants du gouv, qui dédient leur temps libre à rendre la vie un peu plus facile au gens [...]

 Il ne s'agit pas d'une appli que l'on développe avec des amis le week-end. Mais il s'agit d'un outil qui est proposé par le Ministère de l'Intérieur à destination de plus de 60 millions de Français.es pour lutter contre une pandémie et, au passage, pour ne pas être verbalisé de 135 euros. Donc il est plus que normal de s'interroger sur la conformité du document généré, sur les responsabilités juridiques et techniques de chacun et sur le fait (si c'est le cas) pourquoi un outil d'une telle importance soit produit par des développeurs enthousiastes et non par une équipe pro spécialement engagée. (Tout autant que l'on pourrais être surpris d'apprendre que l’on avait confié la création du futur vaccin aux passionnés de la chimie qui font ça dans leur cuisine le soir après le boulot...) Donc je réitère mes questions: **Quelle est l'utilité du champ "Signature" sur un document numérique avec un QR code? Et qui a la responsabilité technique et juridique de cet outil et de l'attestation qu'il génère?** @LAB-MI @philippeBron @cristianpb

(P.S. @a2br Relie attentivement mes questions. À mon sens, ce sont tes commentaires ici et dans les autres discussions qui sont parfois à la limite de la politesse et de l'insolence. Mais on va dire que c'est l'âge. :wink:)

**Comment by a2br** [comment]
@tomchen Tout d'abord, merci de ne pas mettre mes phrases hors de leur contexte, aussi laisse-moi ajouter la suite : 
> Je comprends que cela soit frustrant et que cela n'ait aucun sens

Voilà, c'est mieux. Notez aussi que j'ai utilisé *l'attestation est pensée pour* et pas *l'attestation doit*. Au fond, mon avis concorde avec le vôtre (@andrewgr1812 @tomchen ) : la signature est inutile sur la version numérique. Mais je pars du principe que les policiers ne sont pas totalement idiots et peuvent bien voir que le document n'est pas imprimé, donc impossible à signer pour la majeure partie des gens.

Je vois ce service comme un outil s'ajoutant à l'attestation et s'y adaptant, mais d'après ce que j'ai compris vous le voyez comme un outil auquel l'attestation (son format, ses champs) doit être adaptée -- c'est un point de vue que je comprends, et qui sous certains aspects parait plus logique. Or je doute que les concepteurs de l'application aient le pouvoir d'altérer l'attestation ou les champs qui y figurent. Décevant, je trouve, le gouv devrait être plus coordonné sur ce point-là.

> Il ne s'agit pas d'une appli que l'on développe avec des amis le week-end. Mais il s'agit d'un outil qui est proposé par le Ministère de l'Intérieur à destination de plus de 60 millions de Français.es pour lutter contre une pandémie

A ce sujet, je suis moi aussi assez surpris par le fait que cette application soit si peu complète et adaptée à la version papier qui semble malheureusement primer, puisque le document est pensé pour être imprimé, il y a définitivement quelque chose à faire sur ce point là par le Minint.

> Donc il est plus que normal de s'interroger sur la conformité du document généré, sur les responsabilités juridiques et techniques de chacun et sur le fait (si c'est le cas)

Bien sûr. Moi aussi je m'interroge, seulement je n'envoie pas des messages aigres avec un ton désobligeant. C'est une question très importante du moment qu'on converse avec un minimum respect.

Pour finir, laissez-moi résumer : je suis globalement d'accord avec vous, sauf que je me suis abaissé à écrire un message désagréable à cause d'un autre message désagréable que je n'ai pas apprécié (ou, que j'ai mal interprété, qui sait... ? ).

(P.S. @andrewgr1812 J'ai très bien lu votre message, et les caractères en gras et les points d'interrogations répétés en disent long sur le ton de l'auteur. Je ne ferai à l'inverse pas de remarque sur votre âge. 😉)

**Comment by betalabmi** [comment]
L'attestation mise à disposition l'est dans une version validée par le ministère de l'intérieur et à ce titre, le pdf utilisé pour sa déclinaison numérique est identique à celui rempli manuellement, conformément aux directives reçues. 

Il est à noter que le fait que la signature manuscrite ne soit pas présente sur la version générée n'est pas un défaut de conformité, comme l'ont confirmé les services juridiques du ministère de l'intérieur.

Enfin, pour répondre à un interrogation exprimée dans ce fil de discussion, ce dépôt appartient bien au ministère de l'intérieur (LabMI).

**Comment by a2br** [comment]
@betalabmi Merci beaucoup pour avoir clarifié les zones d'ombre du sujet, dommage que l'information soit peu accessible. Une mention sur le formulaire vaudrait peut-être une PR, non ?
