### ISSUE TITLE
Téléchargement de l'attestation avec Firefox Mobile Android

### ISSUE THREAD

**Issue by EhRom** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#70]
La popup de téléchargement s'affiche, mais le fichier n'est pas téléchargé (version 1.0.4)

**Comment by a2br** [comment]
C'est étrange, la fonction de téléchargement devrait marcher n'importe où à priori...
https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/ca73ef8b11df3d3ddbb394676f7d5415dd658133/src/js/dom-utils.js#L36-L43

**Comment by righy** [comment]
J'ai le même problème. La popup de téléchargement annonce un fichier de 0.04 MB. Puis, en quand je clique sur le bouton télécharger, ça dit que le téléchargement a échoué.

**Comment by Cyrille37** [comment]
Hello
Idem sur mon smartphone Android 10 :
- Google Chrome : Ok
- Firefox light : Ko
- Qwant : Ko
Sur Firefox light une popup avec "Download protocol not supported"

![image](https://user-images.githubusercontent.com/368965/97798478-b96a0480-1c26-11eb-81b6-48fbc630fc73.png)

**Comment by Cyrille37** [comment]
Peut être un indice:

Au chargement de la page https://media.interieur.gouv.fr/deplacement-covid-19/ il y a une erreur javascript dans Firefox sur desktop :
![image](https://user-images.githubusercontent.com/368965/97798529-31d0c580-1c27-11eb-8734-c27228b5a6d5.png)

![image](https://user-images.githubusercontent.com/368965/97798546-54fb7500-1c27-11eb-9c60-91cb45c37304.png)

**Comment by a2br** [comment]
> Peut être un indice:
> 
> Au chargement de la page https://media.interieur.gouv.fr/deplacement-covid-19/ il y a une erreur javascript dans Firefox sur desktop 

Non, ça n'a pas de rapport avec le téléchargement, merci quand même d'avoir pris le temps :)

**Comment by righy** [comment]
Ce serait pas un fantôme de mozilla-mobile/fenix#9735?

**Comment by righy** [comment]
Une mise à jour de Firefox a résolu le problème pour moi.
Avant, j'avais : Firefox Preview 5.0.0
Ça s'est changé en : Firefox Nightly 201031 17:02

**Comment by EhRom** [comment]
C'est un problème d'autorisation dans Android. Firefox n'avait pas le droit d'interagir avec les fichiers. Problème résolu. En revanche la popup de notification induit en erreur, et pourrait avertir du besoin d'autoriser l'accès au système de fichiers.
