### ISSUE TITLE
Pouvoir remplir le formulaire sans tout ressaisir

### ISSUE THREAD

**Issue by mabhub** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#75]
> **Ce ticket n'est pas là pour demander une fonctionnalité,
> mais pour présenter des solutions extérieures.**

La sensibilité des données personnelles est telle que tout implication directe entre celles-ci et ce formulaire est loin d'être simple, et je trouve plutôt *pas absurde* [de ne pas le complexifier](https://fr.wikipedia.org/wiki/Principe_KISS).

Si certain·e·s veulent absolument pouvoir le remplir en un clic, la solution peut aussi simplement venir de *l'extérieur* : une **extension navigateur**, un **[bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet)**, un **[userScript](https://en.wikipedia.org/wiki/Userscript)** (Tampermonkey/Greasemonkey). 
*(Les navigateurs web proposent également parfois nativement des solutions de remplissage de formulaires.)*

Tout celleux capables ici de proposer des <abbr title="Pull Request">PR</abbr> ou évolutions techniques sont très certainement capables de mettre en place au moins l'une de ces solutions alternatives.

Pour ma part j'avais commencé à me faire un bookmarklet, et puis je me suis dit que j'allais probablement devoir en faire d'autre, donc je me suis fait un [générateur de bookmarklet](https://bookmarklet-attestation.netlify.app/) _([libre, open source](https://github.com/mabhub/bookmarklet-attestation-deplacement), etc.)_.

Ça permet d'offrir une solution de **remplissage en un clic** à celleux qui le souhaitent, que ce soit pour eux-même ou pour d'autres _(vous pouvez générer le bookmarklet pour vos proches, parents, amis etc.)_ sans pour autant ajouter une couche (non négligeable) de complexité à un service gouvernemental.

Petite liste non-exhaustive de tickets que ce message concerne sans doute : #50 #27 #13 #43 #9

**Comment by czerkies** [comment]
L'auto-complétion des navigateurs fait très bien le travail.

**Comment by mabhub** [comment]
Oui, globalement.

Mais dans le détail pas toujours. En fait elle fonctionne uniquement pour les champs textes, pas pour les autres types (numérique, date, heure etc.).

**Comment by jmoinet** [comment]
#58 implémente cette fonctionnalité en enregistrant les données localement de manière chiffrée. Ça fonctionne parfaitement et je ne vois pas en quoi cela complexifie quoique ce soit. 
La solution proposée fonctionne sur tous les navigateurs, ce qui n'est pas le cas du workaround proposé ici.

**Comment by a2br** [comment]
La majorité des PR proposant des choses comme le localStorage ne sont pas complexes, ça marche très simplement. D'un autre côté, d'autres changements comme le support des URI fragments peuvent être considérés comme une API publique, qui, dans ton sens, ouvre la porte à des programmes extérieurs cherchant à améliorer le service.
N'empêche que je ne comprends pas pourquoi tu cherches à aller trouver des solutions ailleurs que dans le programme lui-même. Aussi : les meilleurs programmes ne sont pas simples, ils *ont l'air* simple; et il ne faut pas oublier que quelque soit le nom de domaine sur lequel l'app est hébergée, ça reste un générateur de PDF. Rien de compliqué.

**Comment by pierregoutagny** [comment]
Si je suis votre raisonnement @mabhub , ce générateur ne devrait même pas exister. En effet, on pourrait alors s'assurer d'une stricte absence de traitement de données personnelle, et la complexité serait réduite au simple téléchargement d'une attestation vierge en PDF.
De même, je pourrais étendre votre argument sur la capacité des programmeurs contribuant à ce projet à utiliser des extensions de navigateur, en disant que l'on pourrait faire une macro LibreOffice qui remplit tout seul le `.docx` proposé par le ministère, ou un script complétant le `.txt`.
Néanmoins, ce générateur existe. Pourquoi ? Car ses utilisateurs finaux ne sont pas des programmeurs, ou ne savent pas utiliser une extension de navigateur, voire ne peuvent pas en installer (sur mobile, par exemple). C'est à mon avis ce qu'il faut garder à l'esprit quand on décide d'implémenter ou non une fonctionnalité : si *je* sais trouver un autre moyen de le faire, l'utilisateur lambda le peut-il ? Ici, assez clairement, la réponse est non.
Pour finir, je rejoins @jmoinet à propos de la sécurité, la (non-)complexité, et surtout l'universalité de la solution #58 basée sur secure-ls.

**Comment by mabhub** [comment]
Il est curieux que ce ticket génère oppositions et affirmations péremptoires alors qu'il s'agit uniquement là  d'un avis et de l'évocation de l'existence d'alternatives. Il n'est pas question ici d'un rejet unilatéral des propositions faites par ailleurs, mais d'une contextualisation de la problématique.

Le développement communautaire n'est pas une cour de récréation ou combat de coq mais une recherche de consensus.

Peut-être me suis-je mal exprimé initialement pour avoir des réponses qui me semblent autant sur la défensive,… voire offensive.

**Comment by kairos666** [comment]
> L'auto-complétion des navigateurs fait très bien le travail.

l'auto-complétion ne marche pas pour moi sur les champs lieu de naissance, adresse et lieu de naissance.

Dans l'hypothèse où l’auto complétion marcherai pour tous les champs et pour tout le monde tout le temps.... Et bien j'avoue que ce serai la solution la plus claire et simple

**Comment by a2br** [comment]
L'autocompletion n'a pas de valeur 'Lieu de naissance' [à ce que je sache](https://developer.mozilla.org/fr/docs/Web/HTML/Attributs/autocomplete#Valeurs), mais ça devrait marcher pour l'adresse.
