### ISSUE TITLE
Champ d'heure de sortie au mauvais format

### ISSUE THREAD

**Issue by lyriarte** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#77]
Format anglo saxon sur 12H AM/PM, devrait être au format euro sur 24H

**Comment by a2br** [comment]
Merci de lire les autres issues avant d'en ouvrir une. Les sélecteurs de date sont natifs et dépendent donc de votre système (navigateur / OS)

**Comment by abdoulsn** [comment]
#22
