### ISSUE TITLE
Code source non disponible ?

### ISSUE THREAD

**Issue by Alain-DEPUILLE-WDFR** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#8]
Pour conserver la confiance des citoyens, il me semble important de rendre le code source disponible très rapidement.

**Comment by guyou** [comment]
Duplicate #5

**Comment by Alain-DEPUILLE-WDFR** [comment]
[Doublon](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/issues/5)
