### ISSUE TITLE
Erreur de la commande npm run build

### ISSUE THREAD

**Issue by gjgd** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#80]
Quand je lance la commande `npm run build` ou `npm run build:simple` j'obtiens une erreur car PUBLIC_URL n'est pas définie.

Quelle est la bonne manière de définir PUBLIC_URL ?

**Comment by julaudo** [comment]
Il faut lancer `build:dev`, qui positionne cette variable à `'/'`

**Comment by gjgd** [comment]
Oui, mais je voulais savoir comment PUBLIC_URL était définie dans le cadre de la commande build (la commande qui est lancée en prod j'imagine ?)

Est-ce avec un fichier .env par exemple ?

**Comment by julaudo** [comment]
Je ne pense pas qu'il y ait de bonne manière. Une manière est de faire comme c'est fait dans build:dev mais si vous voulez faire autrement, pourquoi pas.

**Comment by theblackhole** [comment]
> Oui, mais je voulais savoir comment PUBLIC_URL était définie dans le cadre de la commande build (la commande qui est lancée en prod j'imagine ?)
> 
> Est-ce avec un fichier .env par exemple ?

Dans les scripts npm, cross-env est utilisé pour définir les variables d'environnement, cela permet de ne pas se soucier de la manière dont les variables sont définies selon windows, linux, etc...

Par exemple la commande `npm run build:dev` execute `cross-env PUBLIC_URL='/' npm run build:simple` qui équivaut simplement à `PUBLIC_URL='/' npm run build:simple` sous Linux/MacOS

Le .env fonctionne mais n'est pas crossplatform et au final, vu qu'il n'y a qu'une seule variable à setter, je pense que `set -o allexport; source .env; set +o allexport; npm run build:simple` est un peu plus long que `PUBLIC_URL='https://example.com' npm run build:simple`

Pour mes propres build j'utilise mon ide pour set la variable, ce qui me permet de faire un build en un clic (+ clean avant) sans avoir à me soucier des paramètres
![image](https://user-images.githubusercontent.com/7818904/97792445-c19e5180-1bde-11eb-8eb2-050eeb23c96a.png)

**Comment by julaudo** [comment]
On a en effet aucune information sur la manière dont c'est fait en production, et visiblement il n'y a pas de CI...

**Comment by gjgd** [comment]
Merci @theblackhole c'est très clair! Donc je suppose qu'en prod ils doivent lancer une commande non définie dans package.json qui set PUBLIC_URL. 

Sinon en regardant où cette variable est utilisée dans le code, il me semble qu'elle devrait plutôt être nommée `URL_PATH`.
Voyez le fichier `index.html`: https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/main/src/index.html#L18 
Il semble que la variable définit la partie "path" de l'URL, '/deplacement-covid-19' dans le cas de la prod.

Du coup dans ton exemple @theblackhole PUBLIC_URL devrait être set à `/` non ?

Je ferme l'issue car j'ai obtenu la réponse à ma question, merci !

**Comment by julaudo** [comment]
La variable est utilisée pour le paramètre --public-url de parcel, c'est pour cela qu'elle est nommé ainsi
