### ISSUE TITLE
npm run serve -- erreur linter

### ISSUE THREAD

**Issue by PPACI** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#84]
Bonjour.

J'ai voulu jouer un peu avec le code et lancer un `npm run serve`.

J'obtiens l'erreur suivante 

```
/home/Pierre/code/github/attestation-deplacement-derogatoire-q4-2020/src/js/form.js
  17:26  error  Extra semicolon  semi
  18:82  error  Extra semicolon  semi
```

https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/main/src/js/form.js#L16

Alors rien de bien méchant en soit, et cela n'est pas une erreur du code en lui même, mais votre linter semble ne pas être en accord avec votre code.

**Comment by a2br** [comment]
https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/pull/60

**Comment by PPACI** [comment]
Parfait 👍
