### ISSUE TITLE
No generation on Android

### ISSUE THREAD

**Issue by MarcDorval** [LAB-MI/attestation-deplacement-derogatoire-q4-2020#94]
No document generated on Android (Samsung Galaxy A50). Same input on a windows PC works fine.

**Comment by betalabmi** [comment]
Bonjour, avec quel navigateur ?

**Comment by MarcDorval** [comment]
Chrome Version 86.0.4240.110

**Comment by MarcDorval** [comment]
Autre question de principe: est-t'il autorisé de sélectionner plusieurs motifs pour une attestation ? Si ce n'est pas le cas, les cases à cocher devraient être remplacées par des radio buttons.

**Comment by okpapt** [comment]
Sur le site officiel, c'est possible.
Si ce n'est pas un bug, faut-il les numéroter dans l'ordre chronologique d'accomplissement ?

**Comment by coralieco** [comment]
L'attestation est bien générée sur Android 😊 mais il n'y a pas de notification de téléchargement, et elle ne se trouve pas non plus dans les "fichiers récents", comme on en a l'habitude avec les documents normalement téléchargés.

=> Pour la retrouver, une fois qu'on a cliqué sur "Générer mon attestation" il faut aller dans "Fichier" et cliquer sur "Téléchargements"

**Comment by MarcDorval** [comment]
Et dans 'téléchargements' il y a... rien. Enfin, dans 'Téléchargements'. Vérifié 10 fois hier soir..

**Comment by MarcDorval** [comment]
D'ailleurs, pas d'indication de download non plus. Comme si l'attestation était bien générée, mais pas transmise au telephone.

**Comment by MarcDorval** [comment]
Vu a l'instant: pas de fichier visible dans 'Téléchargements', mais je trouve bien les attestations dans 'Stockage interne/Download'.
Le mystere reste entier...
![Screenshot_20201102-162114_My Files](https://user-images.githubusercontent.com/26892798/97886382-d424a200-1d28-11eb-82a5-35633398d466.jpg)
![Screenshot_20201102-162130_My Files](https://user-images.githubusercontent.com/26892798/97886384-d4bd3880-1d28-11eb-8160-856aa8d3f592.jpg)

**Comment by MarcDorval** [comment]
C'est a priori un souci dépendant du gestionnaire de fichier utilisé...

**Comment by MarcDorval** [comment]
L'application Samsung 'Mes Fichiers' en Version 11.5.02.391 n'affiche pas les attestations a partir de 'Téléchargements'

**Comment by Tiv0w** [comment]
Le fait de ne pas avoir de notification de téléchargement est potentiellement dépendant :
- de la version Android *et/ou*
- de la potentielle surcouche constructeur/opérateur *et/ou*
- du navigateur.

Quant au fait de ne pas retrouver le PDF dans un emplacement "Téléchargements" ou "Fichiers récents"..., cela dépend encore une fois du trio nommé au-dessus et en plus du gestionnaire de fichiers.

Simplement pour dire qu'il n'est pas vraiment de la responsabilité de ce projet que l'attestation ne soit pas mise en évidence.

**Comment by MarcDorval** [comment]
D'accord. initialement je pensais que les attestations n'etaient pas transmises, hors elles le sont. Il se peut que l'application native n'affiche via le raccourci 'Telechargements' que les fichiers pour lesquels elle a vu passer une notification. En allant avec la meme application dans le dossier 'Downloads' elle affiche alors tous les fichiers presents dans le dossier, dons aussi les attestations.
Il est juste difficile de comprendre un tel comportement, et tout aussi difficile de decrire le chemin a suivre pour arriver au dossier pour le commun des mortels.

**Comment by coralieco** [comment]
En fait, quand on est sur la page du formulaire d'attestation, qu'on clique sur les 3 petits points en haut à droite du navigateur et qu'on clique sur "Paramètres", puis "téléchargement", on voit l'emplacement des fichiers téléchargés. 

Perso, j'ai cet emplacement (voir printscreen) ci dessous.

Sinon, toujours dans au même endroit, dans le navigateur, 3 petits points, "Téléchargements", on voit tous les fichiers qui ont été téléchargés (en tout cas, c'est mon cas).

Contente d'avoir percé le mystère pour ma part :)
 
![signal-2020-11-02-181855](https://user-images.githubusercontent.com/22852543/97898538-46e94980-1d38-11eb-9b0e-8c2fc52526d2.png)

**Comment by MarcDorval** [comment]
Effectivement. Une bonne manip a decrire sur la page !
